AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - lib/c3/**/*
    - lib/d3/**/*
    - lib/github-markdown-css/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
